spring.application.name=backend
#??? ????? db?
spring.datasource.url=jdbc:postgresql://localhost:5433/mydb 
spring.datasource.username=myuser
spring.datasource.password=localdev1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
cors.allowed-origin=http://localhost:4000